build:
  image: node:4.0
  commands:
    - node -v
    - npm -v
    - npm install --quiet
    - npm run typings install
    - npm run tsc
    - npm run lint
cache:
  mount:
    - node_modules
    - typings
